#!/bin/bash


TOKEN=""
CHAT_ID="-1002115809340"
DB_USER="postgres"
DB_PASS=""
DB_NAME="freebyte"
JSON_FILE="/var/lib/marzban/xray_config.json"
SQLITE_FILE="/var/lib/marzban/db.sqlite3"
DB_BACKUP_FILE="/root/backup/freebyte_db_backup.sql"
MESSAGE_THREAD_ID="25166"
CURRENT_DATETIME=$(date +"%Y-%m-%d %H:%M:%S")

export PGPASSWORD=$DB_PASS
pg_dump -U $DB_USER -F c -f $DB_BACKUP_FILE $DB_NAME


send_message_to_telegram() {
    local message=$1
    curl -F chat_id="$CHAT_ID" -F text="$message" -F message_thread_id="$MESSAGE_THREAD_ID" "https://api.telegram.org/bot$TOKEN/sendMessage"
}

send_to_telegram() {
    local file_path=$1
    curl -F chat_id="$CHAT_ID" -F document=@"$file_path" -F message_thread_id="$MESSAGE_THREAD_ID" "https://api.telegram.org/bot$TOKEN/sendDocument"
}

send_message_to_telegram $CURRENT_DATETIME
send_to_telegram $JSON_FILE
send_to_telegram $SQLITE_FILE
send_to_telegram $DB_BACKUP_FILE

echo "Files sent to Telegram successfully."
